### ISSUE TITLE
category/Lo.ts is missing in the deno repositorio

### ISSUE THREAD

**Issue by ModProg** [justjavac/deno_unicode#1]
This leads to the following error:
```
error: Import 'https://deno.land/x/unicode@v0.1.1/category/Lo.ts' failed: 404 Not Found
    at https://deno.land/x/unicode@v0.1.1/mod.ts:4:0
```

![image](https://user-images.githubusercontent.com/11978847/100460149-037bc400-30c7-11eb-9206-512453d1961c.png)

**Comment by justjavac** [comment]
The `Lo.ts` file is too big, 5M+
